# This is a basic workflow to help you get started with Actions

name: Deploy
on:

  # Runs on push to branch "main"
  push:
    branches: [ main ]
    
  # Runs when manually triggered in "Actions" tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ADMIN_IP }}
          username: ${{ secrets.ADMIN_USERNAME }}
          password: ${{ secrets.ADMIN_PASS }}
          port: ${{ secrets.ADMIN_PORT }}
          script: |
            pwd
            whoami
            echo $PATH
            echo $HOME
            git status
            which git
            which composer
            which drush
