name: Deploy
on:

  # Runs on push to branch "main"
  push:
    branches: [ main ]
    
  # Runs when manually triggered in "Actions" tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: SSH Commands
      uses: cross-the-world/ssh-pipeline@master
      with:
        host: ${{ secrets.ADMIN_IP }}
        user: ${{ secrets.ADMIN_USERNAME }}
        pass: ${{ secrets.ADMIN_PASS }}
        port: ${{ secrets.ADMIN_PORT }}
        script: |
          cd ~/admin.andy-blum.com
          echo "-----------------------"
          echo "PULLING RECENT CHANGES"
          echo "-----------------------"
          git fetch
          git pull
          echo "-----------------------"
          echo "INSTALLING DEPENDENCIES"
          echo "-----------------------"
          ~/bin/composer install
          echo "-----------------------"
          echo "CLEARING CACHE"
          echo "-----------------------"
          ~/bin/drush cr
          echo "-----------------------"
          echo "UPDATING DATABASE"
          echo "-----------------------"
          ~/bin/drush updb
          echo "-----------------------"
          echo "IMPORTING CONFIGURATION"
          echo "-----------------------"
          ~/bin/drush cim -y
          echo "-----------------------"
          echo "CLEARING CACHE"
          echo "-----------------------"
          ~/bin/drush cr
