# Because I don't log in frequently enough to remember my password :(
name: Password Reset
on:
    
  # Runs when manually triggered in "Actions" tab
  workflow_dispatch:

jobs:
  reset:
    name: Reset Password
    runs-on: ubuntu-latest
    steps:
    - name: SSH Commands
      uses: cross-the-world/ssh-pipeline@master
      with:
        host: ${{ secrets.ADMIN_IP }}
        user: ${{ secrets.ADMIN_USERNAME }}
        pass: ${{ secrets.ADMIN_PASS }}
        port: ${{ secrets.ADMIN_PORT }}
        script: |
          cd ~/admin.andy-blum.com
          ~/bin/drush uli
